### ISSUE TITLE
mwtab not working

### ISSUE THREAD

**Issue by KMaheswari** [MoseleyBioinformaticsLab/mwtab#1]
mwtab is not working after the recent update in Metabolomics Workbench.
Giving URL error.

**Comment by andreysmelter** [comment]
> mwtab is not working after the recent update in Metabolomics Workbench.
> Giving URL error.

There is currently an issue with SSL certificate on Metabolomics Workbench. I send an email to let them know about the issue.

**Comment by KMaheswari** [comment]
Sure. Thanks for prompt response.

**Comment by andreysmelter** [comment]
Please, update to the latest version of `mwtab`, e.g. `python3 -m pip install mwtab --upgrade`. The issue should be resolved by now.
