### ISSUE TITLE
metabolites with different IDs in different sections

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/mwtab#11]
An example of this is in [ST000017](https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&DataMode=AnalysisData&StudyID=ST000017&StudyType=MS&ResultType=1#DataTabs), positive mode data.

There are multiple metabolites with essentially the same ID:

* 2-HYDROXYBUTYRIC ACID
* 2-HYDROXYBUTYRIC ACID_1
* 2-HYDROXYBUTYRIC ACID_2

Here is the issue. `2-HYDROXYBUTYRIC ACID_1` ID only appears in the **Data** block, and `2-HYDROXYBUTYRIC ACID_2` only appears in the **Metabolites** block. I'm 99% sure that the *1* and *2* in this case are referring to the identical metabolite, but they have different IDs in the **Data** and **Metabolites** sections of the mwtab json.

This feels like something to double check in the validation.

**Comment by rmflight** [comment]
I've also seen this pattern in the same dataset:

* 2'-DEOXYADENOSINE
* 2`-DEOXYADENOSINE
* 2^-DEOXYADENOSINE

**Comment by ptth222** [comment]
Here are the 2 acids from the Metabolites section:

```
{'Metabolite': '2-HYDROXYBUTYRIC ACID',
 'moverz_quant': '',
 'ri': '',
 'ri_type': '',
 'pubchem_id': '11266',
 'inchi_key': '',
 'kegg_id': 'C05984',
 'other_id': '747240_PRIMARY_NOT_UNIQUE',
 'other_id_type': 'UM_Target_ID'}

{'Metabolite': '2-HYDROXYBUTYRIC ACID_2',
 'moverz_quant': '',
 'ri': '',
 'ri_type': '',
 'pubchem_id': '11266',
 'inchi_key': '',
 'kegg_id': 'C05984',
 'other_id': '747634_PRIMARY_NOT_UNIQUE',
 'other_id_type': 'UM_Target_ID'}
```

They are basically the same except for the "other_id". Maybe it's different peaks for the same compound?

In any case I have added code to check that metabolites in the Data section are in the Metabolites section and vice versa. There are actually several more metabolites without exact matches in the example you gave. The commit is dd3610327d37f2b2b8cdecfdc822365c5ebf8bb8. Basically, `validate_file` will now give you an error if there is a metabolite in Data that isn't in Metabolites and vice versa. Is that a satisfactory solution?

**Comment by rmflight** [comment]
That seems like a solution, thanks @ptth222 !
